### ISSUE TITLE
vereinfachen?

### ISSUE THREAD

**Issue by philippgeuder** [fabiantheblind/neighbours#2]
warum baust du kein 2 dimensinales array `list[x][y] = "bla"` aus dem 1 dimensionalen, danach kannst du einfach auf alles drumrum zugreifen:

```
links: list[x-1][y]
rechts list[x+1][y]
oben: list[x][y-1]
unten: list[x][y+1]
```

und für oben rechts etc. halt in kombination.

musst halt nur schauen, dass der index nicht < 0 bzw. > list.length oder list[x].length ist. wenn er das ist, weißte auch, dass du an ner kante bist ;-)

**Comment by ff6347** [comment]
Muss ich mal probieren. Hatte das basierend auf dem Problem einer Studentin geschrieben. Wollte nicht zuviel ändern. 
Aber ja ich Check das mal morgen aus.
